# Generated by Django 5.0.6 on 2024-08-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_guide', '0003_guidetopic_ar_content_guidetopic_ar_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
            ],
        ),
    ]
