# Generated by Django 5.0.6 on 2024-08-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_guide', '0004_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidetopic',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_guide.chapter'),
            preserve_default=False,
        ),
    ]
