# Generated by Django 5.0.6 on 2024-08-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_anouncement_unit_anouncement_college_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anouncement',
        ),
    ]
