# Generated by Django 5.0.6 on 2024-06-01 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university_units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Updated At')),
                ('created', models.DateTimeField(auto_created=True, verbose_name='Created At')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(null=True, upload_to=None, verbose_name='Guide Entry Image')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_units.office', verbose_name='Unit')),
            ],
        ),
    ]
