# Generated by Django 5.0.6 on 2024-06-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_guide', '0002_remove_guidetopic_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidetopic',
            name='ar_content',
            field=models.TextField(default='عربي', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guidetopic',
            name='ar_title',
            field=models.CharField(default='عربي', max_length=128, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
