# Generated by Django 5.0.6 on 2024-08-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_guide', '0005_guidetopic_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidetopic',
            name='ar_content',
            field=models.TextField(verbose_name='Arabic Content'),
        ),
        migrations.AlterField(
            model_name='guidetopic',
            name='ar_title',
            field=models.CharField(max_length=128, verbose_name='Arabic Title'),
        ),
    ]
