# Generated by Django 5.0.6 on 2024-09-27 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_guide', '0007_chapter_ar_title_alter_guidetopic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_guide.chapter'),
        ),
    ]
