# Generated by Django 5.1.1 on 2024-10-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_guide', '0008_chapter_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidetopic',
            name='image',
        ),
    ]
