# Generated by Django 5.0.6 on 2024-08-18 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anouncement',
            name='unit',
        ),
        migrations.AddField(
            model_name='anouncement',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.college', verbose_name='College'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Category Name'),
        ),
    ]
