# Generated by Django 5.0.6 on 2024-08-25 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_anouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='anouncement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Added at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anouncement',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='anouncement',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Announcement Date'),
        ),
    ]
